name: CI-Pipeline

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  day:
    runs-on: ubuntu-latest
    env:
      FAKE_SECRET_TOKEN: 26dbc78b674bc61bd6ac483c9872a1fa36a43917d780dbbf94431160024d956fd320a9a4
      DEPLOY_ENV: staging

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Echo Fake Token
      run: echo "Using token: $FAKE_SECRET_TOKEN"

    - name: Deploy to staging
      run: echo "Deploying to staging with token $FAKE_SECRET_TOKEN"
